// Bundled verification public keys. In production these are the platform's Ed25519 public keys
// shipped *inside* the CLI binary (story E1.4b). For the scaffolding pass we expose a hook
// that test harnesses inject through; at runtime the real keys are loaded from a JSON blob
// that gets generated by the publish pipeline and committed to the repo.
//
// During development the env var DATASETAI_DEV_PUBKEYS_JSON can hold an array of
// { keyId: string; publicKey: string (base64) } so devs can run `install` against a
// hand-rolled local manifest without shipping a new CLI binary.

import type { VerificationKey } from '@datasetai/core';

export function loadVerificationKeys(env: NodeJS.ProcessEnv = process.env): readonly VerificationKey[] {
  const raw = env['DATASETAI_DEV_PUBKEYS_JSON'];
  if (!raw) return [];
  try {
    const parsed = JSON.parse(raw) as Array<{ keyId: string; publicKey: string }>;
    return parsed.map((p) => ({
      keyId: p.keyId,
      publicKey: Uint8Array.from(Buffer.from(p.publicKey, 'base64')),
    }));
  } catch {
    return [];
  }
}
